### ISSUE TITLE
Fails on Non-0 Minimum Value

### ISSUE THREAD

**Issue by paladintodd** [VFPXHome/Gauge#1]
Gauge does not appear to work correctly if you have a non-0 minimum value. I can't see anything in the Fox code that is messing with the values, which makes me think the error lies somewhere in the DLL. 

To recreate the problem, run the SampleGauge form and change the minimum value to 50. You'll see the needle on the gauge goes to 100 rather than being at the 72 value. Additionally, you can turn on the goal marker and set the goal value to 72. The goal marker shows at 86 rather than at 72.

**Comment by DougHennig** [comment]
Fixed in the latest release.
